# Generated by Django 4.1.6 on 2023-02-09 06:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('empApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='fullname',
            field=models.CharField(default='abc', max_length=100),
            preserve_default=False,
        ),
    ]
