# Generated by Django 4.1.6 on 2023-02-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empApi', '0003_alter_employee_emp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='fullname',
            field=models.TextField(max_length=100),
        ),
    ]
