# Generated by Django 4.1.6 on 2023-02-09 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empApi', '0004_alter_employee_fullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='emp_code',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='mobile',
        ),
    ]
