# Generated by Django 4.1.6 on 2023-02-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapi', '0003_alter_crud_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crud',
            name='name',
            field=models.TextField(),
        ),
    ]
