# Generated by Django 4.1.6 on 2023-02-09 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapi', '0004_alter_crud_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crud',
            name='email',
        ),
    ]
