# Generated by Django 4.1.6 on 2023-02-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapi', '0005_remove_crud_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='crud',
            name='email',
            field=models.TextField(default='abc', max_length=40),
            preserve_default=False,
        ),
    ]
